spring:
  application:
    name: DD-AD
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小
  rule:
    #远程规则
    remote:
       - 'https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts' #1024网站及澳门皇家赌场及恶意广告主机列表
       - 'https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad.txt' #halflife-list
       - 'https://raw.githubusercontent.com/lingeringsound/10007_auto/master/adb.txt' #保留广告奖励
       - 'https://www.xlxbk.cn/allow.txt' #白名单
       - 'https://adaway.org/hosts.txt' #AdAway Default Blocklist
       - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #大圣净化
       - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt' #AWAvenue-Adblock-Rule
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
       - 'mylist.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [ADFS Adblock List]
      !  _____    _____                        _____  
      ! |  __ \  |  __ \               /\     |  __ \ 
      ! | |  | | | |  | |  ______     /  \    | |  | |
      ! | |  | | | |  | | |______|   / /\ \   | |  | |
      ! | |__| | | |__| |           / ____ \  | |__| |
      ! |_____/  |_____/           /_/    \_\ |_____/ 
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/afwfv/DD-AD.git
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    文件:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
