logging:
  level:
    org.fordes.adfs: info

application:

  input:
    - name: anti-ad smartdns
      path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf
      type: smartdns

    - name: anti-ad dnsmasq
      path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
      type: dnsmasq

    - name: AdGuard 基础过滤器
      path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
      type: easylist

    - name: Loyalsoldier/clash-rules 广告域名列表
      path: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
      type: clash

    - name: 1Hosts lite
      path: https://o0.pages.dev/Lite/hosts.txt
      type: hosts

  output:
    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        file-header: |
          Test ${total}
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts

  config:
    domain-detect:
      enable: true
      concurrency: 256
      provider:
        - 1.1.1.1