name: Update Filters
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_en.md'
      - '.github/**'
      - '.devcontainer/**'
      - 'LICENSE'
  schedule:
    - cron: 0 */8 * * *
  workflow_dispatch:
    inputs:
      profile:
        required: false
        default: 'prod'
        type: string
        description: 'application running profile'

      should-commit:
        required: false
        default: true
        type: boolean
        description: 'Whether to commit output files'

      release-branch:
        required: false
        default: 'release'
        type: string
        description: 'Release branch name, if should-commit is false, this parameter will be ignored'
env:
  TZ: Asia/Shanghai

jobs:
  Update_Filters:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set default values
        id: defaults
        run: |
          echo "profile=${{ github.event.inputs.profile || 'prod' }}" >> $GITHUB_OUTPUT
          echo "should-commit=${{ github.event.inputs.should-commit || 'true' }}" >> $GITHUB_OUTPUT
          echo "release-branch=${{ github.event.inputs.release-branch || 'release' }}" >> $GITHUB_OUTPUT

      - name: Run Jar
        run:  mvn spring-boot:run -Dspring-boot.run.profiles=${{ steps.defaults.outputs.profile }}

      - name: Archive tracking log
        if: hashFiles('logs/tracking.list') != ''
        uses: actions/upload-artifact@v4
        with:
          name: tracking-log
          path: logs/tracking.list

      - name: Clean up
        if: steps.defaults.outputs.should-commit == 'true'
        run: |
          find . -maxdepth 1 ! -name 'rule' ! -name '.' ! -name '.git' -exec rm -rf {} +
          mv rule/* .
          rm -rf rule

      - name: Set current date
        id: date
        if: steps.defaults.outputs.should-commit == 'true'
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Commit Changes
        id: commit
        if: steps.defaults.outputs.should-commit == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: âœ… auto release at ${{ steps.date.outputs.date }}'
          branch: ${{ steps.defaults.outputs.release-branch }}
          skip_dirty_check: true
          push_options: '--force'
          create_branch: true
          skip_fetch: true
          skip_checkout: true
          commit_options: '--allow-empty'

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
